version: '1.0'
services:
  client:
    build: ./client
    container_name: stin_client
    ports:
      - "80:80"
  server:
    build: ./server
    container_name: stin_server
    ports:
      - "8000:8000"