version: '1.2'
name: "stin"
services:
  client:
    build:
      context: .
      dockerfile: client.dockerfile
    container_name: stin_client
    ports:
      - "80:80"
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: stin_server
    ports:
      - "8000:8000"