# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main", "develop"]
    paths: ["server/**"]
    
  pull_request:
    branches: ["main", "develop"]
    paths: ["server/**"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint
    
      - name: Create coverage files
        run: deno test --allow-all  --coverage=cov_profile

      - name: Create coverage report
        run: deno coverage cov_profile --lcov --output=cov_profile.lcov

            
      - name: Install lcov-summary
        run: |
            npm i -g lcov-summary
            lcov-summary ./cov_profile.lcov | grep "Total Coverage" | cut -d ":" -f 2 | sed -r 's/[%]+//g' | xargs | sed 's/^/ANSWER=/' >> "$GITHUB_ENV"

      - name: Print variables
        run: |
            echo "${{ env }}"

      - name: Create Code Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
            auth: ${{ secrets.GIST_SECRET }}
            gistID: 723c91b7a31aa9f66b300de3fd1dd650
            filename: test.json
            label: Test Coverage
            message: ${{ env.ANSWER }}\%
            valColorRange: ${{ env.ANSWER }}
            maxColorRange: 100
            minColorRange: 70
            color: orange
    

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check


