name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
    - name: Create URL
      run: echo "URL=http://${{ secrets.DEPLOY_IP }}" >> $GITHUB_ENV
      
    - name: Axios Request
      # You may pin to the exact commit or the version.
      # uses: potaesm/github-actions-request@7c5145f0b707e9a1d7b7e71cf1812fcec2228fb5
      uses: potaesm/github-actions-request@1.0.7
      with:
        # `url` is the server URL that will be used for the request
        url: ${{ env.URL }}
        # `method` is the request method to be used when making the request
        method: "POST"
        # `data` is the data to be sent as the request body
        data: ${{ secrets.DEPLOY_PASSWORD }}
